Rails/tweeter4/config/routes.rb
Rails.application.routes.draw do
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"

  resources :users
  resources :sessions
  resources :tweets

  root :to => "tweets#index"

  
  # get 'session/new'

  # get 'session/create'

  # get 'session/destroy'

  # resources :tweets
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/tweeter4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/tweeter4/app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

Rails/tweeter4/app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
end

Rails/tweeter4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Rails/tweeter4/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by name:  params[:username]
		if !@user
  		flash.now.alert = "username #{params[:username]} was invalid"
    	render :new
    elsif @user.password == params[:password]
    	session[:user] = @user.name
    	redirect_to root_url, :notice => "Logged in!" 
    else
  	flash.now.alert = "password was invalid"
    	render :new
    end
  end

  def destroy
    session[:user]=nil
    redirect_to :root, :notice => "Logged out!"
  end
end

Rails/tweeter4/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    if !session[:user]
      redirect_to tweets_path, :alert => "Tienes que hacer login para crear un nuevo tweet"
    else
      @tweet = Tweet.new
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
    if @tweet.user.name != session[:user]
      redirect_to tweets_path, :alert => "No puedes editar un post que no es tuyo!"  
    else
      @tweet = Tweet.find(params[:id])  
    end
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = User.find_by name: session[:user]

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    if @tweet.user.name != session[:user]
      redirect_to tweets_path, :alert => "No puedes borrar el tweet de otro usuario"
    else
      @tweet.destroy
      respond_to do |format|
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:text, :user_id)
    end
end

Rails/tweeter4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
    #respond_to do |format|
      #if @user.save
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        #format.json { render :show, status: :created, location: @user }
      #else
        #format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

Rails/tweeter4/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/tweeter4/app/helpers/session_helper.rb
module SessionHelper
end

Rails/tweeter4/app/helpers/tweets_helper.rb
module TweetsHelper
end

Rails/tweeter4/app/helpers/users_helper.rb
module UsersHelper
end

Rails/tweeter4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <div class="user_nav">
        <% if session[:user] %>
          Logged in as <%= session[:user]%>.
          <%= link_to "Log out", logout_path %>
        <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "log in", login_path %>.
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

Rails/tweeter4/app/views/session/new.html.erb
<%= form_tag("/login", method: "post") do %>
  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username, params[:username] %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password, params[:password] %>
  </div>
  
  <div class="actions"><%= submit_tag "Log in" %></div>
<% end %>

Rails/tweeter4/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/tweeter4/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Rails/tweeter4/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Rails/tweeter4/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Rails/tweeter4/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>